### ISSUE TITLE
Riptide: A Low-Overhead Redundancy for Message Loss

### ISSUE THREAD

**Issue by dberezansky** [Zephyr-Queueing/Quartz#1]
Our current mechanism for feeding messages to a worker (say Isopod0) happens as follows:
1. Isopod0 sends a UDP packet with a batch size to request a workload.
2. Quartz handles the request and dequeues the batch.
3. The batch is sent back via UDP packet(s).
4. Isopod 0 receives and processes batch. Then the process repeats.

Riptide as proposed would add a fail-safe in case a batch response packet is lost in transit containing messages that were just dequeued. The mechanism will enqueue back messages if a new batch request is not received after a determined timeout. This way we preserve the lower overhead benefits of UDP and minimize loss of queue messages as they are distributed to workers.

**Comment by dberezansky** [comment]
Riptide is meant to catch the case where a batch of messages are sent by quartz but they never arrive at a given Isopod instance. Possible cases:
1. Return packet with message dropped (roughly 1 in 10000), timeout will then cause a new request from the Isopod instance and the batch of messages will be lost.
2. Quartz fails to send return packet
Some failure on Server.cpp [send in server.cpp](https://github.com/Zephyr-Queueing/Quartz/blob/b9d9de65c13199824612f8c984d84e83d94861bb/src/Server.cpp#L103).

Approach:
Request packet now will contain batch size and the amount previously received. -1 on the first request, the amount of messages in batch on success, and 0 if timeout or no messages received. 
- On the Quartz end. Last batch cached as local variable, (implement `enqueueFailedBatch()`). Called from where request packet handling logic is implemented.
- On the Isopod end. Local variable keeping track of previous batch, initialized as -1. Updated after request packet sent to 0, then when receiving return packet update again to received total.

@amitferman Did I miss a case? How does the approach sound?

**Comment by dberezansky** [comment]
Riptide feature branches:
https://github.com/Zephyr-Queueing/Quartz/tree/riptide
https://github.com/Zephyr-Queueing/Isopod/tree/riptide

Remaining at this point is implementation of enqueuing failed batch and validation.

**Comment by amitferman** [comment]
Note - Earlier, we updated riptide requests to only contain a boolean indicating whether the last batch was processed as opposed to the last batch size.

Also, to my understanding, riptide corrects up to one batch loss, correct? cc: @dberezansky

**Comment by dberezansky** [comment]
> Also, to my understanding, riptide corrects up to one batch loss, correct? cc: @dberezansky 

Yes, one batch loss at a time. Should cover all that is needed as far as I know.

**Comment by amitferman** [comment]
It will fail to recover two consecutive batch losses, though, correct? And { ith batch loss } are not independent events.

**Comment by dberezansky** [comment]
No, each independent batch return is cached. Any ith batch should be correct as they are independent.

________________________________

**Comment by amitferman** [comment]
Consider the following sequence of events;
1) nth batch lost
2) nth batch resend lost AND (n+1)th batch lost
3) (n+1)th batch resend succeeds and (n+2)th batch succeeds

In this case, the nth batch is never processed. Have I misunderstood riptide?

**Comment by dberezansky** [comment]
It will be processed by someone because it is the next batch to be processed. We are placing it back to the front of the queue system.

________________________________
