### ISSUE TITLE
Riptide 2: "Re-leasing" batch due to worker side failure

### ISSUE THREAD

**Issue by dberezansky** [Zephyr-Queueing/Quartz#4]
Lets define a leased batch as a batch of messages that is neither in the queue nor has it been fully processed on the worker side. The leased batch can fail in one of three elements of the system: (1) on Quartz, (2) over network, (3) on worker. The expected behavior we are looking for on failure is that leased messages that are not confirmed as fully processed will be re-leased as soon as possible (to the front of queue) by another available worker.

Riptide #1 addressed failures that occur (1) on Quartz and (2) over the network through a simple ack by the worker when requesting the next batch. Riptide initially assumed that all players in the exchange were active and working as expected. Riptide v2 exists to add fault tolerance to the system -- in real-world systems a node can fail. Our system should be able to provide a consistent promise that all batches will be processed at least 1 time and that a batch of messages will not be dropped.

Riptide v2 addresses failures that happen (3) on the worker (i.e. worker shut off or worker has failure). The naïve implementation of riptide v2 is a static timeout value such that on timeout the server flushes the last batch. A further iteration with more invest could use data from the worker to optimize this timeout value.

**Comment by dberezansky** [comment]
In further conversation we have identified this issue as a stretch goal, experimentation should be able to safely assume all players are operational. Team goal is either to have this issue resolved 12/8/22 or close the issue as inactive.

**Comment by amitferman** [comment]
In a later conversation, we identified that this issue needs further specification to effectively protect against the case where a worker fails to process a batch after receipt. Therefore, the current Zephyr will not make guarantees about whether batches were _processed_ by workers, and it will focus on providing guarantees for batch receipt.
